Activate virtual environment in Git hooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,25 +1,23 @@
 #!/usr/bin/env bash
 
+if [ -d ".venv" ]; then
+    source .venv/bin/activate
+fi
+
 python_files="moire/ tests/"
 
-echo "Checking code format with Ruff..."
+echo "Check code format with Ruff..."
 if ! ruff format --check ${python_files}; then
-    ruff format --diff --color ${python_files}
+    ruff format --diff ${python_files}
     echo "FAIL"
     exit 1
 fi
 
-echo "Checking types with ty..."
-if ! ty check; then
-    echo "FAIL"
-    exit 1
-fi
+echo "Lint with Ruff..."
+ruff check || { echo "FAIL"; exit 1; }
 
-echo "Linting with Ruff..."
-if ! ruff check; then
-    echo "FAIL"
-    exit 1
-fi
+echo "Check with ty..."
+ty check || { echo "FAIL"; exit 1; }
 
 echo "Run pytest..."
 pytest -v || { echo "FAIL"; exit 1; }
diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,11 +1,17 @@
 #!/usr/bin/env bash
 
+if [ -d ".venv" ]; then
+    source .venv/bin/activate
+fi
+
+echo "Look for changes..."
 files=`git status --porcelain | wc -l`
 if [ ${files} == 0 ] ; then
-    echo "No changes detected. Running pre-push hooks..."
-    .githooks/pre-commit || { echo "FAIL"; exit 1; }
+    echo "OK"
 else
-    echo "Changes detected. Please commit or stash them."
+    echo "FAIL"
     git status
     exit 1
 fi
+
+.githooks/pre-commit || { echo "FAIL"; exit 1; }
